### ISSUE TITLE
PIpeline interruptTransfer requests.

### ISSUE THREAD

**Issue by benvanik** [benvanik/vr.js#14]
It's possible to pipeline interruptTransfer requests to ensure there's no lag in sampling. This may help to increase the sampling rate and reduce latency, at the cost of potentially more CPU usage.

**Comment by pyalot** [comment]
It's difficult to quantify by how much and what's the source, but on Windows 7 (aero disabled, google chrome 26), the lag is substantially bigger than in half-life 2.

In half-life 2 it's probably around 2 frames lag or so. It's definitely more in the range of 10 frames with vr.js.

**Comment by benvanik** [comment]
That's expected, unfortunately - Chrome currently has 5-6 frames of latency through it's input/output flow, meaning that anything built with this will have that as a minimum latency and likely a much higher maximum, based on the user code, device display rate, etc. Work is being done to reduce that number, though I suspect it will always be larger than a real game engine.

**Comment by benvanik** [comment]
This was fixed in https://github.com/benvanik/vr.js/commit/69d108955ec2cd793ffa53d3b5347845c5e99469
